POST http://localhost:3000/tasks
Content-Type: application/json

{
  
    "title": "Buy milk",
    "description": "2% milk"

};

###
GET http://localhost:3000/tasks HTTP/1.1

###
GET http://localhost:3000/tasks/d6be17e2-d08b-4a35-8cfc-b16758af1e95 HTTP/1.1